import SpotifyUserData from "../types/SpotifyUserData";
import LoginRedirect from "../utils/login-redirect";

export default async function createPlaylist(
  eldersBirthYear: number,
  musicalPreference: string,
  spotifyUserData: SpotifyUserData
) {
  try {
    const response = await (
      await fetch(
        `https://api.spotify.com/v1/users/${spotifyUserData.userId}/playlists`,
        {
          headers: {
            "Content-Type": "application/x-www-form-urlencoded",
            Authorization: `Bearer ${spotifyUserData.accessToken}`,
          },
          method: "POST",
          body: JSON.stringify({
            name: `${spotifyUserData.name} ${eldersBirthYear} ${musicalPreference}`,
            description: "Generated by Alive Inside App",
            public: true,
          }),
        }
      )
    ).json();
    if (response.redirect) {
      LoginRedirect();
      return;
    }
    // if (response.error?.status === 401) {
    //   const { accessToken, refreshToken } = await RefreshToken(
    //     spotifyUserData.refreshToken
    //   );
    //   await createPlaylist(eldersBirthYear, musicalPreference, {
    //     ...spotifyUserData,
    //     accessToken,
    //     refreshToken,
    //   });
    //   return;
    // }
    const {
      id,
      external_urls: { spotify: playlistUrl },
    } = response;

    return { url: playlistUrl, id };
  } catch (e) {
    console.error("Error creating Playlist");
    console.error(e);
  }
}
