const CreatePlaylistResponse = {
  collaborative: false,
  description: "Generated by Alive Inside App",
  external_urls: {
    spotify: "https://open.spotify.com/playlist/1xgbCD8h1fER7OzQ4WPGAQ",
  },
  followers: {
    href: null,
    total: 0,
  },
  href: "https://api.spotify.com/v1/playlists/1xgbCD8h1fER7OzQ4WPGAQ",
  id: "1xgbCD8h1fER7OzQ4WPGAQ",
  images: [],
  name: "Gabe Kuslansky 1960 classical",
  owner: {
    display_name: "Gabe Kuslansky",
    external_urls: {
      spotify: "https://open.spotify.com/user/1268037804",
    },
    href: "https://api.spotify.com/v1/users/1268037804",
    id: "1268037804",
    type: "user",
    uri: "spotify:user:1268037804",
  },
  primary_color: null,
  public: true,
  snapshot_id: "MSwzNTk0NjQwYzk4ODU2NTExZjcxYjlkMDA3ZThkOTlhNTE5ZDU1ZDM2",
  tracks: {
    href: "https://api.spotify.com/v1/playlists/1xgbCD8h1fER7OzQ4WPGAQ/tracks",
    items: [],
    limit: 100,
    next: null,
    offset: 0,
    previous: null,
    total: 0,
  },
  type: "playlist",
  uri: "spotify:playlist:1xgbCD8h1fER7OzQ4WPGAQ",
};

export default CreatePlaylistResponse;
